name: Publish

on:
    push:
        tags:
            - v*.*
            - v*
            - v*.*.*

jobs:
    release:
        name: Release
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              shell: bash
              run: |
                tag=$(git describe --tags --abbrev=0)
                release_name="sosnowiecki-txt-$tag"

                7z a -tzip "${release_name}.zip" "assets" "pack.mcmeta" "pack.png"

            - name: Publish
              uses: softprops/action-gh-release@v2
              with:
                files: "sosnowiecki-txt-*"
